stages:
  - dockerbuild-push

package:
  only: 
    - main
  image: docker:latest
  stage: dockerbuild-push
  services:
    - docker:dind
  before_script:
    - docker login -u $GITLAB_USER -p $GITLAB_PASSWORD
  script:
    - docker build -t $GITLAB_USER/$PROJECT_NAME . 
    - docker push $GITLAB_USER/$PROJECT_NAME
  after_script:
    - docker logout
